language: android
jdk:
- oraclejdk8
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
- openssl aes-256-cbc -K $encrypted_e8c7a373402f_key -iv $encrypted_e8c7a373402f_iv
  -in google.p12.enc -out .\\google.p12 -d
- openssl aes-256-cbc -K $encrypted_6ca2067ed10f_key -iv $encrypted_6ca2067ed10f_iv
  -in keystore.jks.enc -out keystore.jks -d
- mkdir -p ~/.gradle
- echo "georentingKeystorePassword=$KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
- echo "testfairyKey=$TESTFAIRY_KEY" >> ~/.gradle/gradle.properties

script:
- "./gradlew testfairyInternalRelease"
- if [ "$TRAVIS_TAG" ]; then ./gradlew publishProductionRelease; fi;