language: android
jdk:
- oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - BUILD_TYPE=assembleAll
  - BUILD_TYPE=testfairyRelease
  - BUILD_TYPE=productionRelease

android:
  components:
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-23
  - addon-google_apis-google-23

before_install:
- openssl aes-256-cbc -K $encrypted_6ca2067ed10f_key -iv $encrypted_6ca2067ed10f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p ~/.gradle
- echo "georentingKeystorePassword=$KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
- echo "testfairyKey=$TESTFAIRY_KEY" >> ~/.gradle/gradle.properties
- rvm use 2.2.2 --install --binary --fuzzy
- gem install fastlane

script:
- if [ "$BUILD_TYPE" == "assembleAll" ]; then ./gradlew assemble; fi;
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$BUILD_TYPE" == "testfairyRelease" ]; then ./gradlew testfairyInternalRelease; fi;
- if [ "$TRAVIS_TAG" ] && [ "$BUILD_TYPE" == "productionRelease" ]; then scripts/prepareEmulator.sh; fastlane beta; fi;

notifications:
  slack:
    rooms:
      - alternadev:DV4HmorAz8nFcc4rxBdy92ke#android

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "./app/build/outputs/apk/app-production-release.apk"
    - "./app/build/outputs/apk/app-internal-release.apk"
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_TYPE = assembleAll
