language: android
jdk:
- oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_6ca2067ed10f_key -iv $encrypted_6ca2067ed10f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p ~/.gradle
- echo "georentingKeystorePassword=$KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
- echo "testfairyKey=$TESTFAIRY_KEY" >> ~/.gradle/gradle.properties
script:
- "./gradlew assemble"
- "./gradlew testfairyInternalRelease"
- if [ "$TRAVIS_TAG" ]; then ./gradlew publishProductionRelease; fi;
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "./app/build/outputs/apk/app-production-release.apk"
    - "./app/build/outputs/apk/app-internal-release.apk"
  skip_cleanup: true
  on:
    tags: true