language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_6ca2067ed10f_key -iv $encrypted_6ca2067ed10f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p ~/.gradle
- echo "georentingKeystorePassword=$KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
- echo "testfairyKey=$TESTFAIRY_KEY" >> ~/.gradle/gradle.properties
script:
- "./gradlew testfairyInternalRelease"
- if [ "$TRAVIS_TAG" ]; then ./gradlew publishProductionRelease; fi;
