# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :android

platform :android do
  before_all do
  end


  desc "Submit a new Alpha Build to Google Play Beta"
  lane :alpha do
    # Disabled until automatic screenshots work.
    # gradle(task: "assembleProductionDebug")
    # gradle(task: "assembleProductionDebugAndroidTest")
    # screengrab
    gradle(task: "assembleProductionRelease")
    supply track: 'alpha', apk_paths: ["./app/build/outputs/apk/app-production-release.apk"]
  end

  desc "Submit a new Beta Build to Google Play Beta"
  lane :beta do
    # Disabled until automatic screenshots work.
    # gradle(task: "assembleProductionDebug")
    # gradle(task: "assembleProductionDebugAndroidTest")
    # screengrab
    gradle(task: "assembleProductionRelease")

    build_number = Integer(ENV['TRAVIS_BUILD_NUMBER']) + 1000

    sh "mkdir -p #{ENV['TRAVIS_BUILD_DIR']}/fastlane/metadata/android/en-US/changelogs/"
    sh "curl https://api.github.com/repos/alternaDev/georenting-android/releases/tags/#{ENV['TRAVIS_TAG']} | jq '.body' >> #{ENV['TRAVIS_BUILD_DIR']}/fastlane/metadata/android/en-US/changelogs/#{build_number}.txt"

    supply track: 'alpha', apk_paths: ["./app/build/outputs/apk/app-production-release.apk"]
    supply track: 'alpha', track_promote_to: 'beta', skip_upload_apk: true, skip_upload_metadata: true, skip_upload_screenshots: true, skip_upload_images: true
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
